# Use an official Python runtime as a base image
FROM python:latest

#Create working directory
RUN mkdir -p /usr/src/ADS_Final
RUN mkdir -p /usr/src/ADS_Final/Data

# Set the working directory to /usr/src/ADS_Final
WORKDIR /usr/src/ADS_Final

# Copy the current directory contents into the container at /usr/src/ADS_Final
COPY *.txt *.py *.json *.sh /usr/src/ADS_Final/

# Bundle ADS_Final source
COPY . /usr/src/ADS_Final

RUN chmod +x /usr/src/ADS_Final/run.sh

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
RUN pip install jupyter notebook

# Make port 8888 available to the world outside this container
EXPOSE 8888